---
# Tasks specific for Debian/Ubuntu Systems

- name: "Debian | Set some facts"
  set_fact:
      zabbix_agent: zabbix-agent
  tags:
    - zabbix-agent
    - init

- name: "Debian | download repo package"
  get_url: url="http://repo.zabbix.com/zabbix/{{ zabbix_version }}/debian/pool/main/z/zabbix-release/zabbix-release_{{ zabbix_version }}-1+wheezy_all.deb"
           dest="/tmp/zabbix-release_{{ zabbix_version }}-1+wheezy_all.deb" mode=0440
  when: ansible_distribution == "Debian" and zabbix_repo == "zabbix"
  sudo: yes
  tags:
    - zabbix-agent
    - init

- name: "Debian | Installing deb repository Ubuntu"
  apt: deb="/tmp/zabbix-release_{{ zabbix_version }}-1+wheezy_all.deb"
  when: ansible_distribution == "Debian" and zabbix_repo == "zabbix"
  sudo: yes
  tags:
    - zabbix-agent
    - init

- name: "Debian | download repo package"
  get_url: url="http://repo.zabbix.com/zabbix/{{ zabbix_version }}/ubuntu/pool/main/z/zabbix-release/zabbix-release_{{ zabbix_version }}-1+trusty_all.deb"
           dest="/tmp/zabbix-release_{{ zabbix_version }}-1+trusty_all.deb" mode=0440
  when: ansible_distribution == "Ubuntu" and zabbix_repo == "zabbix"
  sudo: yes
  tags:
    - zabbix-agent
    - init

- name: "Debian | Installing deb repository Ubuntu"
  apt: deb="/tmp/zabbix-release_{{ zabbix_version }}-1+trusty_all.deb"
  when: ansible_distribution == "Ubuntu" and zabbix_repo == "zabbix"
  sudo: yes
  tags:
    - zabbix-agent
    - init

- name: "Debian | Installing zabbix-agent"
  apt: pkg={{ zabbix_agent_package }}
       state=present
       update_cache=yes
  sudo: yes
  tags:
    - zabbix-agent
    - init

- name: "Debian | Enable the service"
  service: name={{ zabbix_agent_service }}
           enabled=yes
  sudo: yes
  tags:
    - zabbix-agent
    - init
    - service
